feat: `Fs` adds `copy` & `link`, `TokioFs` & `TokioUringFs` & `Monoio` have been implemented
tonbo-io/fusio pull request #100
Opened 2024-11-11 09:39 UTC by KKould

ref: https://github.com/tonbo-io/fusio/issues/99

2024-11-14 08:13 UTC, ethe requested changes
Shall we fix CI first?

2024-11-14 08:17 UTC, ethe commented on fusio-opendal/src/fs.rs
> +        todo!()
return unsupported should be fine

2024-11-14 08:24 UTC, ethe commented on fusio/src/fs/mod.rs
> +                .write_all("🎵never gonna give you up🎵".as_bytes())
🕺🕺🕺

2024-11-14 08:25 UTC, ethe commented on fusio/src/impls/disk/monoio/fs.rs
> +        fs::copy(&from, &to)?;
spawn or spawn blocking here

2024-11-14 08:27 UTC, ethe commented on fusio/src/impls/disk/monoio/fs.rs
> +        fs::copy(&from, &to)?;
also below

2024-11-15 04:09 UTC, ethe commented on fusio/src/impls/disk/monoio/fs.rs
> +        let _ = monoio::spawn(async move { fs::hard_link(&from, &to) }).await?;
it should catch the return result here

2024-11-15 09:52 UTC, ethe approved these changes

2024-11-15 11:21 UTC, KKould commented
Please wait for the pr: https://github.com/tonbo-io/tonbo/pull/219 approval before merging

2024-11-19 08:11 UTC, merged